### ISSUE TITLE
Instructions for Lexemes

### ISSUE THREAD

**Issue by belett** [maxlath/wikidata-cli#69] opened 2019-01-31 12:05 UTC
Hi,

Would it be possible to have instructions for Lexemes? Or at least to think about it ;)

There is no tool right now, probably because the API is not fully ready and still unstable. SO it would be nice if CLI could fill this gap.

**Comment by maxlath** [comment] 2019-05-17 20:41
closing this issue as it's a duplicate of #57
it could be that I take the opportunity of this wmhack edition to give it a shot but can't promise ;)

**Closed by maxlath** 2019-05-17 20:41 UTC
Labels: feature request
